version: '3'

services:
  databases:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - '3010:3306'
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  server:
    container_name: MyServer
    build: .
    ports:
      - '3000:3000'